django_apps/django_apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('user_auth.urls')),
    url(r'', include("django.contrib.auth.urls"))
]

django_apps/user_auth/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user_auth'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="user_auth/login.html"), name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
]

django_apps/user_auth/models.py
from django.contrib import auth


class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

django_apps/user_auth/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):

    class Meta:

        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Avatar Name'
        self.fields['email'].label = 'Email Address'

django_apps/user_auth/views.py
from django.views.generic import CreateView
from .forms import UserCreateForm
from django.core.urlresolvers import reverse_lazy


class SignUp(CreateView):

    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'user_auth/signup.html'

django_apps/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <title>Star Social</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css' %}">


</head>

<body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="#">Star Social</a>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="#" class="btn btn-simple">Post</a></li>
                    <li><a href="#" class="btn btn-simple">Groups</a></li>
                    <li><a href="#" class="btn btn-simple">Create Group</a></li>
                    <li><a href="{% url 'user_auth:logout' %}" class="btn btn-simple">Log out</a></li>
                {% else %}
                    <li><a href="#" class="btn btn-simple">Groups</a></li>
                    <li><a href="{% url 'user_auth:login' %}" class="btn btn-simple">Log in</a></li>
                    <li><a href="{% url 'user_auth:signup' %}" class="btn btn-simple">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}

    </div>
    <canvas id="canvas">
    </canvas>
</body>
</html>

django_apps/user_auth/templates/user_auth/login.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

django_apps/user_auth/templates/user_auth/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}